#import "../../macros.typ": *

//setup basics
#import "@preview/rubber-article:0.4.1": *
#import "@preview/ergo:0.2.0": *
#import "@preview/fletcher:0.5.5" as fletcher: *

//basic template setup
#show: article.with(
  header-display: true,
  eq-numbering: "(1.1)",
  eq-chapterwise: true,
  margins: 1.0in,
)
#show: ergo-init.with(
    colors: ergo-colors.penumbra-light,  
    styles: ergo-styles.classic, 
    breakable: true,
    inline-qed: true
)

//start document
#maketitle(
  title: "Math 231A HW 7",
  authors: ("Zih-Yu Hsieh",),
  date: datetime.today().display("[month repr:long] [day], [year]"),
)

= D//1
#problem[
  Etingof Lecture Notes Exercise 15.5:

  Prove Lemma 15.4:
  #lemma[
    The quotient $frak(g)\/[frak(g),frak(g)]$ is abelian; moreover, if $I subset.eq frak(g)$ is an ideal such that $frak(g)\/I$ is abelian, then $I supset.eq [frak(g),frak(g)]$.
  ][]
][
  First, to show that the Lie bracket on the quotient of a Lie ideal is well-defined, given any $x,x',y,y' in frak(g)$ such that $overline(x)=overline(x')$ and $overline(y)=overline(y')$ under $frak(g)\/I$, where $I$ is a Lie ideal. Then, this indicates that $x-x', y-y' in I$. Hence, by the property that $I$ is a Lie ideal, we have the following:
  $ [x,y]-[x,y']=[x,y-y'] in I ==> overline([x,y])=overline([x,y']) $
  $ [x,y']-[x',y']=[x-x',y'] in I ==> overline([x,y']) =overline([x',y']) $
  Hence, this indicates that the quotient $overline([x,y])=overline([x',y'])$, showing that the Lie bracket is well-defined on the level of quotient. Hence, it's well-defined to set $[overline(x),overline(y)]:= overline([x,y])$.

  \ 

  Now, given any $overline(x), overline(y) in frak(g)\/[frak(g),frak(g)]$, since $[overline(x),overline(y)] = overline([x,y]) = 0$ (since $[x,y] in [frak(g),frak(g)]$), then $frak(g)\/[frak(g),frak(g)]$ is abelian.

  \ 

  Finally, given that $frak(g)\/I$ is abelian for a Lie ideal $I$, then given any $x,y in frak(g)$, we have that $[overline(x),overline(y)] = overline([x,y]) = 0$, showing that $[x,y] in I$. Hence, since all the generators of $[frak(g),frak(g)]$ is contained in $I$, we have $[frak(g),frak(g)] subset.eq I$.
]

#pagebreak()

#set enum(numbering: "(i)")
= ND//2
#problem[
  Etingof Lecture Notes Exercise 15.7:

  + Prove that if $G$ is a connected Lie group with Lie algebra $frak(g)$ then the group commutant $[G,G]$ (the subgroup of $G$ generated by elements $g h g^(-1) h^(-1)$, $g,h in G$) is a Lie subgroup of $G$ with Lie algebra $[frak(g),frak(g)]$.
  + Let $tilde(G) = RR times H$, where $H$ is the #emph[Heisenberg Group] of real matrices of the form 
    $ M(a,b,c):= mat(1,a,b;0,1,c;0,0,1), quad a,b,c in RR $
    Let $Gamma tilde.equiv ZZ^2 subset tilde(G)$ be the (closed) central subgroup generated by the pairs $(1,M(0,0,0) = id)$ and $(sqrt(2), M(0,0,1))$. Let $G = tilde(G)\/Gamma$. Show that $[G,G]$ is not closed in $G$ (although by (i) it is a Lie subgroup).

  + Does $[G,G]$ have to be closed in $G$ if $G$ is simply-connected? (Consider $Hom(G,RR)$ and apply the second fundamental theorem of Lie theory).
][
  
]

#pagebreak()

= D//3
#problem[
  Etingof Lecture Notes Exercise 15.11:

  Prove Proposition 15.10:
  #proposition[
    + Any Lie subalgebra or quotient of a solvable Lie algebra is solvable.
    + If $I subset.eq frak(g)$ is an ideal and $I,frak(g)\/I$ are solvable, then $frak(g)$ is solvable.
  ][]
][
  + First, given a solvable Lie algebra $frak(g)$, suppose $frak(h) subset.eq frak(g)$ is a subalgebra. Then, we'll prove by induction that the derived series of $frak(h)$ is always contained in $frak(g)$'s series.

    For $n=1$, all $x,y in frak(h)$ has $[x,y] in [frak(g),frak(g)]$, so all generators of $[frak(h),frak(h)]$ is contained in $[frak(g),frak(g)]$, showing $D^1(frak(h)) =[frak(h),frak(h)] subset.eq [frak(g),frak(g)] = D^1(frak(g))$,.

    Now, suppose given $n in NN$, $n-1<n$ satisfies $D^(n-1)(frak(h)) subset/eq D^(n-1)(frak(g))$. Then,for any $x,y in D^(n-1)(frak(h))$, we have $[x,y] in [D^(n-1)(frak(g)),D^(n-1)(frak(g))] = D^n (frak(g))$, so all generators of $D^(n)(frak(h))=[D^(n-1)(frak(h)),D^(n-1)(frak(h))]$ is contained in $D^(n)(frak(g))$, showing $D^n (frak(h)) subset.eq D^n (frak(g))$. Hence, by induction one concludes that all $D^n (frak(h)) subset.eq D^n (frak(g))$.

    As a result, since $D^n (frak(g))=0$ for some $n in NN$ by solvability, then it enforces $D^n(frak(h)) = 0$, showing $frak(h)$ is also solvable.

    \ 

    Now, given any Lie ideal $I subset.eq frak(g)$ and the quotient map $pi:frak(g) arrow.r.twohead frak(g)\/I$ (for simplicity, let $frak(k)=frak(g)\/I$). Again, we'll prove by induction that the derived series of $frak(k)$ is the image of $frak(g)$'s derived series.

    For $n=1$, since for all $overline(x), overline(y) in frak(k)$ satisfies $[overline(x),overline(y)]=overline([x,y]) = pi([x,y])$, hence the generators of $D^1(frak(k))=[frak(k),frak(k)]$ is contained in $pi(D^1(frak(g))) = pi([frak(g),frak(g)])$, hence $D^1(frak(k)) subset.eq pi(D^1(frak(g)))$. Conversely, it also suggests that the generators $[x,y]$ of $D^(1)(frak(g))$ has image contained in $D^(1)(frak(k))$, hence $pi(D^(1)(frak(g))) subset.eq D^(1)(frak(k))$. This concludes that $pi(D^(1)(frak(g)))=D^(1)(frak(k))$.

    Now, suppose given $n in NN$, $n-1<n$ satisfies $D^(n-1)(frak(k)) = pi(D^(n-1)(frak(g)))$. Then, for any $overline(x), overline(y) in D^(n-1)(frak(k)) = pi(D^(n-1)(frak(g)))$ (where they correspond to the image of some $x,y in pi(D^(n-1)(frak(g)))$), one has $[overline(x),overline(y)] = overline([x,y])$, where $[x,y] in [D^(n-1)(frak(g)), D^(n-1)(frak(g))] = D^(n)(frak(g))$. This shows that $overline([x,y]) in pi(D^(n)(frak(g)))$, hence all generators of $D^(n)(frak(k))=[D^(n-1)(frak(k)),D^(n-1)(frak(k))]$ is contained in $pi(D^(n)(frak(g)))$, therefore $D^(n)(frak(k)) subset.eq pi(D^(n)(frak(g)))$. Conversely, this also shows that generators of $D^(n)(frak(g))$ (all $[x,y]$ with $x,y in D^(n-1)(frak(g))$) satisfies $pi([x,y]) in D^(n)(frak(k))$, hence $pi(D^(n)(frak(g))) subset.eq D^(n)(frak(k))$. THis concludes that $pi(D^(n)(frak(g)))=D^(n)(frak(k))$.
    So, by induction one concludes that all $D^(n)(frak(k)) = pi(D^(n)(frak(g)))$.

    As a result, since $D^(n)(frak(g))=0$ for some $n in NN$ by solvability, then it also enforces $D^(n)(frak(k))=0$ (since $pi(D^(n)(frak(g)))=0$), showing $frak(k)$ is also solvable.

    \ 

    \ 

  + Now, suppose that both $I$ and $frak(g)\/I = frak(k)$ are solvable (with quotient map $pi:frak(g)arrow.r.twohead frak(g)\/I$). The goal is to show the derived series eventually is contained in $I$, which we'll heavily utilize the statement in (i).

    Since in (i) we've proven that $D^(n)(frak(k))=pi(D^(n)(frak(g)))$ for all $n in NN$, hence by solvability of $frak(k)$, there exists $n in NN$, where $pi(D^(n)(frak(g)))= D^(n)(frak(k))=0$. This implies that $D^(n)(frak(g)) subset.eq I$. However, since $D^(n)(frak(g))$ is now a subalgebra of $I$, with $I$ being solvable, the statement in (i) implies $D^(n)(frak(g))$ is also solvable, hence for some $k in NN$, $D^(k)(D^(n)(frak(g)))=0$.

    Finally, it suffices to realize that $D^(k)(D^(n)(frak(g)))=D^(n+1)(frak(g))$:
    
    Since $D^1(D^(n)(frak(g))) = [D^(n)(frak(g)),D^(n)(frak(g))] = D^(n+1)(frak(g))$, and by induction if $k-1<k$ satisfies $D^(k-1)(D^(n)(frak(g)))=D^(n+k-1)(frak(g))$, thenn $D^(k)(D^(n)(frak(g))) = [D^(k-1)(D^(n)(frak(g))),D^(k-1)(D^(n)(frak(g)))]=[D^(n+k-1)(frak(g)),D^(n+k-1)(frak(g))] = D^(n+k)(frak(g))$. 

    So, we have $0=D^(k)(D^(n)(frak(g)))=D^(n+k)(frak(g))$, showing $frak(g)$ is solvable.
]

\ 

= D//4
#problem[
  Etingof Lecture Notes Exercise 15.16:

  Prove Proposition 15.15:
  #proposition[
    Any Lie subalgebra or quotient of a nilpotent Lie algebra is nilpotent.
  ][]
][
  First, suppose $frak(g)$ is a nilpotent Lie algebra, with $frak(h) subset.eq frak(g)$ being a subalgebra. To show the nilpotency of $frak(h)$, it suffices to show its Lower Central Series is always contained in $frak(g)$'s Lower Central Series.

  For $n=1$, it's clear that $D_1(frak(h))=[frak(h),frak(h)]subset.eq [frak(g),frak(g)]=D_1(frak(g))$ (for proof cf. #text(weight: "bold")[Problem 3 part (i)]).

  Now, suppose for given $n in NN$, it satisfies $D_(n-1)(frak(h)) subset.eq D_(n-1)(frak(g))$. Then for $D_(n)(frak(h)) = [D_(n-1)(frak(h)),frak(h)]$, since all its generators are of the form $[x,y]$, where $x in D_(n-1)(frak(h)) subset.eq D_(n-1)(frak(g))$ and $y in frak(h) subset.eq frak(g)$, so $[x,y] in [D_(n-1)(frak(g)),frak(g)] = D_(n)(frak(g))$. Hence, all generators of $D_(n)(frak(h))$ is contained in $D_(n)(frak(g))$, showing $D_(n)(frak(h)) subset.eq D_(n)(frak(g))$. Hence, by induction all $n in NN$ satisfies $D_(n)(frak(h)) subset.eq D_(n)(frak(g))$.

  As a result, since $frak(g)$ is nilpotent, there exists $k in NN$, where $D_(k)(frak(g))=0$, and it enforces $D_(k)(frak(h))=0$ also, so $frak(h)$ is nilpotent.

  \ 

  Now, given an ideal $I subset.eq frak(g)$, and the quotient map $pi:frak(g) arrow.r.twohead frak(g)\/I$ (for simplicity again, denote $frak(g)\/I = frak(k)$). We'll show its Lower Central Series is always contained in the image of $frak(g)$'s Lower Central Series.

  For $n=1$,it's also clear that $D_1(frak(k)) = D^1(frak(k)) subset.eq pi(D^1(frak(g))) = pi(D_1(frak(g)))$ (again, cf. #text(weight: "bold")[Problem 3 part (i)]).

  Now, suppose for given $n in NN$, it satisfies $D_(n-1)(frak(k)) subset.eq pi(D_(n-1)(frak(g)))$, then for $D_(n)(frak(k)) = [D_(n-1)(frak(k)),frak(k)]$, the generators are of the form $[overline(x),overline(y)]$, where $overline(x) in D_(n-1)(frak(k)) subset.eq pi(D_(n-1)(frak(g)))$ (say corresponds to the image of $x in D_(n-1)(frak(g))$), and $overline(y) in frak(k)$ (say corresponds to the image of $y in frak(g)$). Then, since $[overline(x),overline(y)] = overline([x,y])$, where $[x,y] in [D_(n-1)(frak(g)),frak(g)] = D_(n)(frak(g))$, showing that $[overline(x),overline(y)] in pi(D_(n)(frak(g)))$. Hence, $D_(n)(frak(k)) subset.eq pi(D_(n)(frak(g)))$ (since all generators satisfy this relation). Therefore, by induction every $n in NN$ satisfies $D_(n)(frak(k)) subset.eq pi(D_(n)(frak(g)))$.


  As a result, since $frak(g)$ is nilpotent, there exists $k in NN$ where $D_(k)(frak(g))=0$, which enforces $D_(k)(frak(k))=0$ also (since $pi(D_(k)(frak(g)))=0$). So, $frak(k)$ is also nilpotent.
]