#import "../../macros.typ": *

//setup basics
#import "@preview/rubber-article:0.4.1": *
#import "@preview/ergo:0.2.0": *
#import "@preview/fletcher:0.5.5" as fletcher: *

//basic template setup
#show: article.with(
  header-display: true,
  eq-numbering: "(1.1)",
  eq-chapterwise: true,
  margins: 1.0in,
)
#show: ergo-init.with(
    colors: ergo-colors.penumbra-light,  
    styles: ergo-styles.classic, 
    breakable: true,
    inline-qed: true
)

//start document
#maketitle(
  title: "Math 231A HW 7",
  authors: ("Zih-Yu Hsieh",),
  date: datetime.today().display("[month repr:long] [day], [year]"),
)

= D//1
#problem[
  Etingof Lecture Notes Exercise 15.5:

  Prove Lemma 15.4:
  #lemma[
    The quotient $frak(g)\/[frak(g),frak(g)]$ is abelian; moreover, if $I subset.eq frak(g)$ is an ideal such that $frak(g)\/I$ is abelian, then $I supset.eq [frak(g),frak(g)]$.
  ][]
][
  First, to show that the Lie bracket on the quotient of a Lie ideal is well-defined, given any $x,x',y,y' in frak(g)$ such that $overline(x)=overline(x')$ and $overline(y)=overline(y')$ under $frak(g)\/I$, where $I$ is a Lie ideal. Then, this indicates that $x-x', y-y' in I$. Hence, by the property that $I$ is a Lie ideal, we have the following:
  $ [x,y]-[x,y']=[x,y-y'] in I ==> overline([x,y])=overline([x,y']) $
  $ [x,y']-[x',y']=[x-x',y'] in I ==> overline([x,y']) =overline([x',y']) $
  Hence, this indicates that the quotient $overline([x,y])=overline([x',y'])$, showing that the Lie bracket is well-defined on the level of quotient. Hence, it's well-defined to set $[overline(x),overline(y)]:= overline([x,y])$.

  \ 

  Now, given any $overline(x), overline(y) in frak(g)\/[frak(g),frak(g)]$, since $[overline(x),overline(y)] = overline([x,y]) = 0$ (since $[x,y] in [frak(g),frak(g)]$), then $frak(g)\/[frak(g),frak(g)]$ is abelian.

  \ 

  Finally, given that $frak(g)\/I$ is abelian for a Lie ideal $I$, then given any $x,y in frak(g)$, we have that $[overline(x),overline(y)] = overline([x,y]) = 0$, showing that $[x,y] in I$. Hence, since all the generators of $[frak(g),frak(g)]$ is contained in $I$, we have $[frak(g),frak(g)] subset.eq I$.
]

#pagebreak()

#set enum(numbering: "(i)")
= D//2
#problem[
  Etingof Lecture Notes Exercise 15.7:

  + Prove that if $G$ is a connected Lie group with Lie algebra $frak(g)$ then the group commutant $[G,G]$ (the subgroup of $G$ generated by elements $g h g^(-1) h^(-1)$, $g,h in G$) is a Lie subgroup of $G$ with Lie algebra $[frak(g),frak(g)]$.
  + Let $tilde(G) = RR times H$, where $H$ is the #emph[Heisenberg Group] of real matrices of the form 
    $ M(a,b,c):= mat(1,a,b;0,1,c;0,0,1), quad a,b,c in RR $
    Let $Gamma tilde.equiv ZZ^2 subset tilde(G)$ be the (closed) central subgroup generated by the pairs $(1,M(0,0,0) = id)$ and $(sqrt(2), M(0,1,0))$. Let $G = tilde(G)\/Gamma$. Show that $[G,G]$ is not closed in $G$ (although by (i) it is a Lie subgroup).

  + Does $[G,G]$ have to be closed in $G$ if $G$ is simply-connected? (Consider $Hom(G,RR)$ and apply the second fundamental theorem of Lie theory).
][
  + WLOG, we'll take the universal cover $tilde(G)$ instead of $G$, since the covering map $p:tilde(G) arrow.r G$ is a local diffeomorphism satisfying $p([tilde(G),tilde(G)]) = [G,G]$ ($[tilde(G),tilde(G)]$ is a subgroup generated by the paths of the form $[x(t) y(t) x(t)^(-1) y(t)^(-1)]$, which gets mapped down to $x(1)y(1)x(1)^(-1)y(1)^(-1) in [G,G]$. Since $G$ is connected, $x(1),y(1)$ can be arbitrary, so the generators of $[G,G]$ is contained in $p([tilde(G),tilde(G)])$, hence $[G,G] subset.eq p([tilde(G),tilde(G)])$; the other direction is given by the fact that every generator of $[tilde(G),tilde(G)]$ is mapped into $[G,G]$, hence $p([tilde(G),tilde(G)]) subset.eq [G,G]$). Then, if proving that $[tilde(G),tilde(G)]$ is a submanifold corresponding to $[frak(g),frak(g)]$, it follows from the covering map that $[G,G] = p([tilde(G),tilde(G)])$ is also a submanifold corresponding to $[frak(g),frak(g)]$ (since the evenly covered neighborhood of $1 in G$ and $[1] in tilde(G)$ shows that their tangent space must be isomorphic via the differential of covering map $p_*$, hence also isomorphic as Lie Algebra).

    To comprehend this, on the Lie algebra level, we have the following "exact sequence" (where $pi$ is the quotient map):
    #set align(center)
    #diagram($
              0 edge(->) & [frak(g),frak(g)] edge("hook->") & frak(g) edge(->>, script(pi)) & frak(g)\/[frak(g),frak(g)] edge(->) & 0
            $)
    #set align(left)
    Using Fundamental Theorem of Lie Theory (equivalence of categories between simply-connected Lie groups and Lie algebras), take the simply-connected Lie group of $frak(g)$ (which $tilde(G)$ satisfies this), and $tilde(K)$ of $frak(g)\/[frak(g),frak(g)]$. The Second Fundamental Theorem of Lie Theory states the bijection between $Hom(tilde(G),tilde(K)) arrow.r.tilde Hom(frak(g),frak(g)\/[frak(g),frak(g)])$ by sending the Lie group homomorphism $phi mapsto phi_*$, hence for the quotient map $pi:frak(g) arrow.r frak(g)\/[frak(g),frak(g)]$, there exists a unique Lie group homomorphism $phi:tilde(G) arrow.r tilde(K)$, such that $phi_*=pi$. Which, let $H:=ker(phi)$ be a Lie subgroup of $tilde(G)$, it forms the following correspondance of exact sequences:
    #set align(center)
    #diagram($
              0 edge(->) & H edge("hook->") & tilde(G) edge(->>, script(phi)) & tilde(K) edge(->) & 0\ 
              0 edge(->) & [frak(g),frak(g)] edge("hook->") & frak(g) edge("u",->, script(exp_(tilde(G)))) edge(->>, script(pi=phi_*)) & frak(g)\/[frak(g),frak(g)] edge("u",->, script(exp_(tilde(K)))) edge(->) & 0
            $)
    #set align(left)
    Which, this correspondance also shows that $Lie(H) = [frak(g),frak(g)]$: Given any $x in [frak(g),frak(g)]$, since they satisfy the following:
    $ phi compose exp_(tilde(G))(x) = exp_(tilde(K)) compose pi(x) = exp_(tilde(K))(0)=1_tilde(K) $
    then $exp_(tilde(G))(x) in ker(phi)=H$, hence $[frak(g),frak(g)] subset.eq Lie(H)$; on the other hand, take $H sect U$ (where $U subset.eq tilde(G)$ is the domain of $log_(tilde(G))$ function), then any $h in H sect U$ satisfies the following (recall that $log$ is inverse of $exp$ on some open subset):
    $ pi compose log_(tilde(G))(h) = log_(tilde(K)) compose phi(h) = log_(tilde(K))(1_tilde(K)) = 0 $
    Hence, showing that the tangent space $Lie(H) subset.eq ker(pi) = [frak(g),frak(g)]$. So, the full correspondance is as follow:
    #set align(center)
    #diagram($
              0 edge(->) & H edge("hook->") & tilde(G) edge(->>, script(phi)) & tilde(K) edge(->) & 0\ 
              0 edge(->) & [frak(g),frak(g)] edge("u",->,script(exp_(H))) edge("hook->") & frak(g) edge("u",->, script(exp_(tilde(G)))) edge(->>, script(pi=phi_*)) & frak(g)\/[frak(g),frak(g)] edge("u",->, script(exp_(tilde(K)))) edge(->) & 0
            $)
    #set align(left)

    \ 

    Now, since $frak(g)\/[frak(g),frak(g)]$ is abelian Lie algebra, then it indicates that $tilde(K)$ is an abelian Lie group, in particular $[tilde(G),tilde(G)] subset.eq ker(phi)=H$ (since image of $phi$ is abelian).

    For the reverse direction, given any $x,y in frak(g)$, we have the curve $e^(t x)e^y e^(-t x)e^(-y):RR arrow.r G$ satisfies the following:
    $ log(e^(t x)e^y e^(-t x)e^(-y))/t &= log(Ad_(e^(t x))(e^y)e^(-y))/t = log(exp(Ad_(e^(t x)*)y)e^(-y))/t\ 
    &= (Ad_(e^(t x)*)dot y + (-y) + [Ad_(e^(t x)*)dot y, -y] + ...)/t\ 
    &= (exp(ad(t x))(y) -y + [exp(ad(t x))(y), -y] + ...)/t\ 
    &= (sum_(n=0)^infinity t^n/n! ad(x)^n (y) - y - sum_(n=0)^infinity t^n/n! [ad(x)^n (y),y]+...)/t\ 
    &= (y+t ad(x)(y) + sum_(n=2)^infinity t^n/n! ad(x)^n(y) - y - [y, y]-sum_(n=1)^infinity t^n/n![ad(x)^n (y), y]+...)/t \
    &= ad(x)(y) + (sum_(n=2)^infinity t^(n-1)/n! ad(x)^n (y) - sum_(n=1)^infinity t^(n-1)/n! [ad(x)^n (y),y]+...) $
    Which, the eventual $...$ using BCH formula can be seen that it involves higher order terms of $Ad_(e^(t x)*)(y)$ bracketing with $y$, hence expanding $Ad_(e^(t x)*) = exp(ad(t x))$, the zeroth order term cancels (by bracketing with $y$ itself), while every other term has degree of $t$ being greater than $1$. Hence, take $lim_(t arrow.r 0)log(e^(t x)e^y e^(-t x)e^(-y))/t$, the above formula provides $ad(x)(y) = [x,y]$. 

    Since the curve $e^(t x)e^y e^(-t x)e^(-y) subset [tilde(G),tilde(G)]$, one has $exp([x,y]) in [tilde(G),tilde(G)]$; also, since all $[x,y]$ are generators of $[frak(g),frak(g)]$, its exponentiation should generate a subgroup containing in $[tilde(G),tilde(G)]$. Finally, with $H$ being generated by exponentiation of $[frak(g),frak(g)]$, we conclude that $H subset.eq [tilde(G),tilde(G)]$. Hence, we must have $[tilde(G),tilde(G)]=H$, showing $[tilde(G),tilde(G)]$ is in fact a Lie subgroup.

    With the covering map claim, $p([tilde(G),tilde(G)]) = [G,G]$ is also a Lie subgroup of $G$ (since it's an immersed submanifold).
    
    
    \ 

    \ 

  + Since the projection $pi:tilde(G) arrow.r tilde(G)\/Gamma = G$ defines the topology of $G$ through quotient topology, to show that $[G,G]$ is not closed, it suffices to compute the preimage $pi^(-1)([G,G])$ being not closed (since under quotient topology, a subset $V$ is closed iff its preimage is closed).

    First, given any $g,h in tilde(G)$, we have the commutator $pi(g h g^(-1) h^(-1))$ being a commutator of $pi(g),pi(h)$ instead, so $pi$ sends generators of $[tilde(G),tilde(G)]$ to $[G,G]$, showing $pi([tilde(G),tilde(G)]) subset.eq [G,G]$. Also, since the projection $pi$ is surjective, then for every $g',h' in G$, there exists $g,h in tilde(G)$ in the fibre of $g',h'$ respectively. Which, $g' h' g'^(-1) h'^(-1) = pi(g h g^(-1) h^(-1))$, showing generators of $[G,G]$ is contained in $pi([tilde(G),tilde(G)])$, hence $[G,G] subset.eq pi([tilde(G),tilde(G)])$. So, $[G,G] = pi([G,G])$.

    Hence, for all $g in pi^(-1)([G,G])$, there is an $h in [tilde(G),tilde(G)]$, such that $pi(g)=pi(h)$, or $pi(h^(-1)g)=1$, hence $h^(-1)g in Gamma$, showing $g in h Gamma subset [tilde(G),tilde(G)]Gamma$, showing $pi^(-1)([G,G]) subset.eq [tilde(G),tilde(G)]Gamma$. (which, because $[tilde(G),tilde(G)]$ is normal and $Gamma$ is central, $[tilde(G),tilde(G)] Gamma$ is a well-defined subgroup). Conversely, all element in $[tilde(G),tilde(G)]Gamma$ is of the form $a b$ where $a in [tilde(G),tilde(G)]$ and $b in Gamma$, so $pi(a b)=pi(a) pi(b) = pi(a)$, where $pi(a) in [G,G]$, showing that $pi([tilde(G),tilde(G)]Gamma) subset.eq [G,G]$, hence $[tilde(G),tilde(G)]Gamma subset.eq pi^(-1)([G,G])$. So, $pi^(-1)([G,G]) = [tilde(G),tilde(G)]Gamma$.

    \ 

    Now, based on the claim, it suffices to compute that $[tilde(G),tilde(G)]Gamma$ is not closed. Given any $(x, M(a,b,c)), (y, M(d,e,f)) in tilde(G)$, their commutator is given as follow:
    $ &[(x,M(a,b,c)),(y,M(d,e,f))] = (x+y-x-y, [M(a,b,c),M(d,e,f)])\ 
    &= (0, mat(1,a,b;0,1,c;0,0,1)mat(1,d,e;0,1,f;0,0,1)mat(1,a,b;0,1,c;0,0,1)^(-1)mat(1,d,e;0,1,f;0,0,1)^(-1))\ 
    &= (0,mat(1,a,a f+b+e;0,1,c+f;0,0,1)mat(1,-a,-b+a c;0,1,-c;0,0,1)mat(1,-d,-e+d f;0,1,-f;0,0,1))\ 
    &= (0,mat(1,0,(-b+a c)+a(-c)+(a f+b+e);0,1,-c+(c+f);0,0,1)mat(1,-d,-e+d f;0,1,-f;0,0,1))\ 
    &= (0,mat(1,0,a f+e;0,1,f;0,0,1)mat(1,-d,-e+d f;0,1,-f;0,0,1))\ 
    &= (0,mat(1,0,a f+d f;0,1,0;0,0,1)) $
    Which, this shows that generators is contained in the subgroup $K = {(0,M(0,x,0)) | x in RR}$, or $[tilde(G),tilde(G)] subset.eq K$; also, take $a=x,f=1$, and $d=0$, then the above commutator generates $(0,M(0,x,0))$, hence we have $[tilde(G), tilde(G)]=K$.

    Finally, since $Gamma = angle.l (1,M(0,0,0)),(sqrt(2),M(0,1,0)) angle.r$ is central, everything has the structure of $(1,M(0,0,0))^n (sqrt(2),M(0,1,0))^m = (n+m sqrt(2), M(0,m,0))$ based on matrix computation (where $n,m in ZZ$). So, with $[tilde(G),tilde(G)] = K = {(0,M(0,x,0)) | x in RR}$, we have the following:
    $ (0,M(0,x,0))(n+m sqrt(2),M(0,m,0)) = (n+m sqrt(2)M(0,x+m,0)) $
    Hence, this indicates that $[tilde(G),tilde(G)]Gamma = {(n+m sqrt(2),M(0,x+m,0)) | n,m in ZZ, quad x in RR}$. But, notice that this is not closed, since one can choose the subset where $x = -m$, so the corresponding subset is ${(n+m sqrt(2),M(0,0,0)) | n,m in ZZ}$. Since the subset ${n+m sqrt(2) | n,m in ZZ} subset RR$ is dense (but not spanning the whole $RR$), we have for instance $(sqrt(3),M(0,0,0))$ being a limit point but not in the set (since if $sqrt(3)=n+m sqrt(2)$, one has $2=n^2+2m^2+2 n m sqrt(2)$; yet with $sqrt(2)$ being irrational, we must have $n m=0$, showing $n=0$ or $m=0$. But, $n=0$ implies $sqrt(3)=m sqrt(2)$, or $3=2 m^2$ is a contradiction by parity; similarly, $m=0$ implies $sqrt(3)=n$ is also a contradiction by rationality). So, $(sqrt(3),M(0,0,0)) in.not [tilde(G),tilde(G)]Gamma$, but is a limit point, showing that $[tilde(G),tilde(G)]Gamma = pi^(-1)([G,G])$ is not closed, so is $[G,G]$.
    
    \ 

    \ 

  + If $G$ is simply-connected, by the Second Fundamental Theorem of Lie Theorey, the map $Hom(G,RR) arrow.r Hom(frak(g),Lie(RR))$ by sending the Lie group homomorphism $phi mapsto phi_*$ defines a bijection.

    Since as Lie group $RR$ is abelian (under addition), hence every Lie group hommorphism $phi:G arrow.r RR$ satisfies $[G,G] subset.eq ker(phi)$, hence on the tangent space level, we have $[frak(g),frak(g)] = Lie([G,G]) subset.eq Lie(ker(phi)) = ker(phi_*)$ (Note: such correspondance is true, because of the equality $phi compose exp_(G) = exp_(RR) compose phi_*$, hence $x in ker(phi_*)$ iff $exp_(RR) compose phi_*(x) = exp_(RR)(0) = 0_RR$ iff $phi compose exp_(G)(x) = 0_RR$ iff $exp_(G)(x) in ker(phi)$, showing the tangent space of $ker(phi)$ is $ker(phi_*)$). This also indicates that $[frak(g),frak(g)] subset.eq sect.big_(phi in Hom(G,RR))ker(phi_*)$. 

    Now, we claim the inclusion is in fact equality: Given any $x in.not [frak(g),frak(g)]$, choose a basis $ell_1,...,ell_k$ for $[frak(g),frak(g)]$, then $ell_1,...,ell_k, x$ is linearly independent in $frak(g)$, hence can be extended to a basis of $frak(g)$, say $ell_1,...,ell_k,x,f_1,...,f_l$ (say $frak(g)$ is $k+l+1$-dimension).
    THen, define the Linear functional $phi_(x):frak(g) arrow.r RR$ by $phi_(x)(f_i)=phi_(x)(ell_j)=0$, while $phi_(x)(x)=1$. This is in fact a well-defined Lie algebra homomorphism, since given any $a,b in frak(g)$, one has $[a,b] in [frak(g),frak(g)]=span{ell_1,...,ell_k}$, hence $phi_(x)([a,b]) = 0 = [phi_(x)(a),phi_(x)(b)]$ (recall that $RR=Lie(RR)$, and it's abelian, so every Lie bracket is $0$). So, there exists $phi_(x) in Hom(frak(g),Lie(RR))$, such that $x in.not ker(phi_(x))$, showing that $x in.not sect.big_(phi in Hom(G,RR))ker(phi_*)$. In other words, one must have $sect.big_(phi in Hom(G,RR))ker(phi_*) subset.eq [frak(g),frak(g)]$, showing $[frak(g),frak(g)]=sect.big_(phi in Hom(G,RR))ker(phi_*)$.

    \ 

    As a result, first since each $phi in Hom(G,RR)$ satisfies $[G,G] subset.eq ker(phi)$, so $[G,G] subset.eq sect.big_(phi in Hom(G,RR))ker(phi)$ as subgroup due to the property of abelianization.
    
    Also, if we consider some open neighborhood of $1$, say $U$ such that $exp_G$ is a diffeomorphism with inverse $log$ (which $U$ generates $G$), since each $ker(phi)$ is a closed Lie subgroup generated by $U sect exp_(G)(ker(phi_*)) = U sect ker(phi)$ (exponentiation of their own tangent space), then if consider $U sect (sect.big_(phi in Hom(G,RR))ker(phi)) = sect.big_(phi in Hom(G,RR))(U sect ker(phi)) = sect.big_(phi in Hom(G,RR))(U sect exp_(G)(ker(phi_*)))$ (which generates $sect.big_(phi in Hom(G,RR))ker(phi)$ as groups, not manifold yet), since $U$ is where $exp_G$ becomes a diffeomorphism (in particular a bijection), then $sect.big_(phi in Hom(G,RR))(U sect exp_(G)(ker(phi_*)))$ must be exponentiated from subsets of $sect.big_(phi in Hom(G,RR))ker(phi_*) = [frak(g),frak(g)]$ (since then $log(U sect exp_(G)(ker(phi_*))) subset.eq ker(phi_*)$, so $log(sect.big_(phi in Hom(G,RR))(U sect exp_(G)(ker(phi_*)))) = sect.big_(phi in Hom(G,RR))log(U sect exp_(G)(ker(phi_*))) subset.eq sect.big_(phi in Hom(G,RR))ker(phi_*) = [frak(g),frak(g)]$). 

    So, $sect.big_(phi in Hom(G,RR))ker(phi)$ can be generated by exponentiation of subsets of $[frak(g),frak(g)]$, which is contained in $[G,G]$ (which has tangent space $[frak(g),frak(g)]$). Hence, $[G,G] = sect.big_(phi in Hom(G,RR))ker(phi)$.

    With each $ker(phi)$ being closed Lie subgroup, this indicates that $[G,G]$ as their intersection is closed. So, $G$ being simply-connected implies $[G,G]$ is closed.
]

#pagebreak()

= D//3
#problem[
  Etingof Lecture Notes Exercise 15.11:

  Prove Proposition 15.10:
  #proposition[
    + Any Lie subalgebra or quotient of a solvable Lie algebra is solvable.
    + If $I subset.eq frak(g)$ is an ideal and $I,frak(g)\/I$ are solvable, then $frak(g)$ is solvable.
  ][]
][
  + First, given a solvable Lie algebra $frak(g)$, suppose $frak(h) subset.eq frak(g)$ is a subalgebra. Then, we'll prove by induction that the derived series of $frak(h)$ is always contained in $frak(g)$'s series.

    For $n=1$, all $x,y in frak(h)$ has $[x,y] in [frak(g),frak(g)]$, so all generators of $[frak(h),frak(h)]$ is contained in $[frak(g),frak(g)]$, showing $D^1(frak(h)) =[frak(h),frak(h)] subset.eq [frak(g),frak(g)] = D^1(frak(g))$,.

    Now, suppose given $n in NN$, $n-1<n$ satisfies $D^(n-1)(frak(h)) subset/eq D^(n-1)(frak(g))$. Then,for any $x,y in D^(n-1)(frak(h))$, we have $[x,y] in [D^(n-1)(frak(g)),D^(n-1)(frak(g))] = D^n (frak(g))$, so all generators of $D^(n)(frak(h))=[D^(n-1)(frak(h)),D^(n-1)(frak(h))]$ is contained in $D^(n)(frak(g))$, showing $D^n (frak(h)) subset.eq D^n (frak(g))$. Hence, by induction one concludes that all $D^n (frak(h)) subset.eq D^n (frak(g))$.

    As a result, since $D^n (frak(g))=0$ for some $n in NN$ by solvability, then it enforces $D^n(frak(h)) = 0$, showing $frak(h)$ is also solvable.

    \ 

    Now, given any Lie ideal $I subset.eq frak(g)$ and the quotient map $pi:frak(g) arrow.r.twohead frak(g)\/I$ (for simplicity, let $frak(k)=frak(g)\/I$). Again, we'll prove by induction that the derived series of $frak(k)$ is the image of $frak(g)$'s derived series.

    For $n=1$, since for all $overline(x), overline(y) in frak(k)$ satisfies $[overline(x),overline(y)]=overline([x,y]) = pi([x,y])$, hence the generators of $D^1(frak(k))=[frak(k),frak(k)]$ is contained in $pi(D^1(frak(g))) = pi([frak(g),frak(g)])$, hence $D^1(frak(k)) subset.eq pi(D^1(frak(g)))$. Conversely, it also suggests that the generators $[x,y]$ of $D^(1)(frak(g))$ has image contained in $D^(1)(frak(k))$, hence $pi(D^(1)(frak(g))) subset.eq D^(1)(frak(k))$. This concludes that $pi(D^(1)(frak(g)))=D^(1)(frak(k))$.

    Now, suppose given $n in NN$, $n-1<n$ satisfies $D^(n-1)(frak(k)) = pi(D^(n-1)(frak(g)))$. Then, for any $overline(x), overline(y) in D^(n-1)(frak(k)) = pi(D^(n-1)(frak(g)))$ (where they correspond to the image of some $x,y in pi(D^(n-1)(frak(g)))$), one has $[overline(x),overline(y)] = overline([x,y])$, where $[x,y] in [D^(n-1)(frak(g)), D^(n-1)(frak(g))] = D^(n)(frak(g))$. This shows that $overline([x,y]) in pi(D^(n)(frak(g)))$, hence all generators of $D^(n)(frak(k))=[D^(n-1)(frak(k)),D^(n-1)(frak(k))]$ is contained in $pi(D^(n)(frak(g)))$, therefore $D^(n)(frak(k)) subset.eq pi(D^(n)(frak(g)))$. Conversely, this also shows that generators of $D^(n)(frak(g))$ (all $[x,y]$ with $x,y in D^(n-1)(frak(g))$) satisfies $pi([x,y]) in D^(n)(frak(k))$, hence $pi(D^(n)(frak(g))) subset.eq D^(n)(frak(k))$. THis concludes that $pi(D^(n)(frak(g)))=D^(n)(frak(k))$.
    So, by induction one concludes that all $D^(n)(frak(k)) = pi(D^(n)(frak(g)))$.

    As a result, since $D^(n)(frak(g))=0$ for some $n in NN$ by solvability, then it also enforces $D^(n)(frak(k))=0$ (since $pi(D^(n)(frak(g)))=0$), showing $frak(k)$ is also solvable.

    \ 

    \ 

  + Now, suppose that both $I$ and $frak(g)\/I = frak(k)$ are solvable (with quotient map $pi:frak(g)arrow.r.twohead frak(g)\/I$). The goal is to show the derived series eventually is contained in $I$, which we'll heavily utilize the statement in (i).

    Since in (i) we've proven that $D^(n)(frak(k))=pi(D^(n)(frak(g)))$ for all $n in NN$, hence by solvability of $frak(k)$, there exists $n in NN$, where $pi(D^(n)(frak(g)))= D^(n)(frak(k))=0$. This implies that $D^(n)(frak(g)) subset.eq I$. However, since $D^(n)(frak(g))$ is now a subalgebra of $I$, with $I$ being solvable, the statement in (i) implies $D^(n)(frak(g))$ is also solvable, hence for some $k in NN$, $D^(k)(D^(n)(frak(g)))=0$.

    Finally, it suffices to realize that $D^(k)(D^(n)(frak(g)))=D^(n+1)(frak(g))$:
    
    Since $D^1(D^(n)(frak(g))) = [D^(n)(frak(g)),D^(n)(frak(g))] = D^(n+1)(frak(g))$, and by induction if $k-1<k$ satisfies $D^(k-1)(D^(n)(frak(g)))=D^(n+k-1)(frak(g))$, thenn $D^(k)(D^(n)(frak(g))) = [D^(k-1)(D^(n)(frak(g))),D^(k-1)(D^(n)(frak(g)))]=[D^(n+k-1)(frak(g)),D^(n+k-1)(frak(g))] = D^(n+k)(frak(g))$. 

    So, we have $0=D^(k)(D^(n)(frak(g)))=D^(n+k)(frak(g))$, showing $frak(g)$ is solvable.
]

\ 

= D//4
#problem[
  Etingof Lecture Notes Exercise 15.16:

  Prove Proposition 15.15:
  #proposition[
    Any Lie subalgebra or quotient of a nilpotent Lie algebra is nilpotent.
  ][]
][
  First, suppose $frak(g)$ is a nilpotent Lie algebra, with $frak(h) subset.eq frak(g)$ being a subalgebra. To show the nilpotency of $frak(h)$, it suffices to show its Lower Central Series is always contained in $frak(g)$'s Lower Central Series.

  For $n=1$, it's clear that $D_1(frak(h))=[frak(h),frak(h)]subset.eq [frak(g),frak(g)]=D_1(frak(g))$ (for proof cf. #text(weight: "bold")[Problem 3 part (i)]).

  Now, suppose for given $n in NN$, it satisfies $D_(n-1)(frak(h)) subset.eq D_(n-1)(frak(g))$. Then for $D_(n)(frak(h)) = [D_(n-1)(frak(h)),frak(h)]$, since all its generators are of the form $[x,y]$, where $x in D_(n-1)(frak(h)) subset.eq D_(n-1)(frak(g))$ and $y in frak(h) subset.eq frak(g)$, so $[x,y] in [D_(n-1)(frak(g)),frak(g)] = D_(n)(frak(g))$. Hence, all generators of $D_(n)(frak(h))$ is contained in $D_(n)(frak(g))$, showing $D_(n)(frak(h)) subset.eq D_(n)(frak(g))$. Hence, by induction all $n in NN$ satisfies $D_(n)(frak(h)) subset.eq D_(n)(frak(g))$.

  As a result, since $frak(g)$ is nilpotent, there exists $k in NN$, where $D_(k)(frak(g))=0$, and it enforces $D_(k)(frak(h))=0$ also, so $frak(h)$ is nilpotent.

  \ 

  Now, given an ideal $I subset.eq frak(g)$, and the quotient map $pi:frak(g) arrow.r.twohead frak(g)\/I$ (for simplicity again, denote $frak(g)\/I = frak(k)$). We'll show its Lower Central Series is always contained in the image of $frak(g)$'s Lower Central Series.

  For $n=1$,it's also clear that $D_1(frak(k)) = D^1(frak(k)) subset.eq pi(D^1(frak(g))) = pi(D_1(frak(g)))$ (again, cf. #text(weight: "bold")[Problem 3 part (i)]).

  Now, suppose for given $n in NN$, it satisfies $D_(n-1)(frak(k)) subset.eq pi(D_(n-1)(frak(g)))$, then for $D_(n)(frak(k)) = [D_(n-1)(frak(k)),frak(k)]$, the generators are of the form $[overline(x),overline(y)]$, where $overline(x) in D_(n-1)(frak(k)) subset.eq pi(D_(n-1)(frak(g)))$ (say corresponds to the image of $x in D_(n-1)(frak(g))$), and $overline(y) in frak(k)$ (say corresponds to the image of $y in frak(g)$). Then, since $[overline(x),overline(y)] = overline([x,y])$, where $[x,y] in [D_(n-1)(frak(g)),frak(g)] = D_(n)(frak(g))$, showing that $[overline(x),overline(y)] in pi(D_(n)(frak(g)))$. Hence, $D_(n)(frak(k)) subset.eq pi(D_(n)(frak(g)))$ (since all generators satisfy this relation). Therefore, by induction every $n in NN$ satisfies $D_(n)(frak(k)) subset.eq pi(D_(n)(frak(g)))$.


  As a result, since $frak(g)$ is nilpotent, there exists $k in NN$ where $D_(k)(frak(g))=0$, which enforces $D_(k)(frak(k))=0$ also (since $pi(D_(k)(frak(g)))=0$). So, $frak(k)$ is also nilpotent.
]