#import "../../macros.typ": *

//start document
#show: ergo-init.with(
    colors: "bootstrap",  
    headers: "classic", //"tab" for upper bar, classic for the one I used, sidebar for the emphasis on the left
    all-breakable: true,
    inline-qed: true,
)

#maketitle(
  title: "Math 237A HW 1",
  authors: ("Zih-Yu Hsieh",),
  date: datetime.today().display("[month repr:long] [day], [year]"),
)

= ND (b)//1
#problem[
  Lazarsfeld Problem Set 1 (1):

  Let $k$ be an algebraically closed field, and let $M_(n times n) = AA^(n^2)(k)$ be the affine space of all $n times n$ matrices with entries in $k$. Determine which of the following subsets of $M_(n times n)$ are algebraic:

  (a) $SL(n) := {A in M_(n times n)|det(A)=1}$.

  (b) $"Diag"(n) := {A in M_(n times n) | A "can be diagonalized"}$.

  (c) $"Nilp"(n) := {A in M_(n times n)|A "is nilpotent"}$.
][

  #text(weight: "bold")[(a):] Given $det:M_(n times n) arrow.r k$, it is in fact a polynomial function in $k[x_(11),...,x_(n n)]$ (polynomial ring with all entries of $n times n$ matrix as indeterminates). Which, if consider $det - 1 in k[x_(11),...,x_(n n)]$, for any $A in M_(n times n)$, we have $det(A)-1=0 <==> A in SL(n)$. This shows that $SL(n) = Z(det-1)$, the algebraic set corresponding to the polynomial $det-1$.

  \ 

  #text(weight: "bold")[(b):]

  \ 

  #text(weight: "bold")[(c):] First, recall that for any matrix $A in M_(n times n)(k)$ (viewed as a linear operator on vector space $k^n$), its minimal polynomial $m_A (x) in k[x]$ has $deg(m_A)<= n = dim(k^n)$.
  
  On the other hand, if $A$ is nilpotent, that means $A^k = 0$ for some $k in NN$. Hence, $A$ is a matrix satisfying the polynomial $x^k in k[x]$, showing that the minimal polynomial $m_A (x)$ divides $x^k$, or $m_A(x) = x^l$ for some $l in NN$, and $l<= n$ based on the previous conditions. Hence, for all $A in "Nilp"(n)$, we have $A^n=0$ (since $A$ has minimal polynomial $m_A (x) = x^l$ with $l<=n$, so $A^n = A^(n-l) A^l = A^(n-1)dot 0=0$); conversely, if $A^n = 0$ by definition we have $A in "Nilp"(n)$. Therefore, we conclude that $A in "Nilp"(n) <==> A^n=0$.
  
  Now, let $X = mat(x_(11),x_(12),..., x_(1 n); x_(21),x_(22),...,x_(2n); dots.v, dots.v, dots.down, dots.v; x_(n 1), x_(n 2),..., x_(n n))$ be the matrix of indeterminates, and consider the matrix $X^n = mat(f_(11), f_(12),...,f_(1n); f_(21),f_(22),...,f_(2n); dots.v,dots.v, dots.down, dots.v; f_(n 1), f_(n 2), ..., f_(n n))$ (where each $f_(i j) in k[x_(11),...,x_(n n)]$), we claim that $"Nilp"(n) = Z((f_(i j))_(1<=i,j<=n))$, the algebraic set generated by all the entries of $X^n$.

  For all $A in M_(n times n)$, plug $X=A$ into the polynomials, we get that $A^n$ has each entry $a_(i j) = f_(i j)(A)$ (where the variables are plugged in with entries of $A$), hence the previous statement states that $A in "Nilp"(n) <==> A^n = 0 <==> a_(i j) = f_(i j)(A) = 0$ for all $1<=i,j<= n$. Therefore, the algebraic set $Z((f_(i j)_(1<=i,j<=n))) = "Nilp"(n)$ (since satisfying these equations is equivalent to the matrix being nilpotent).
]

\ 

= D//2
#problem[
  Lazarsfeld Problem Set 1 (4):

  Let $n>=2$, and let $f in k[x_1,...,x_n]$ be a non-constant polynomial over an algebraically closed field $k$. Show that $X={f=0} subset.eq AA^n$ is infinite. When $k=CC$, show that $X$ is non-compact in the classical topology.
][
  For $n>=2$, one can view $k[x_1,...,x_n] = R[x_n]$ (where $R = k[x_1,...,x_(n-1)]$, and $R$ is not a field, since $n-1 >=1$, so there are indeterminates used in $R$). Then, for all $(a_1,...,a_(n-1)) in AA^(n-1)$, one can consider $f(a_1,...,a_(n-1), x_n) in k[x_n]$ (since plugging in $a_1,...,a_(n-1)$ for indeterminates $x_1,...,x_(n-1)$, $f$ is left with only one indeterminate $x_n$), then because $k$ is algebraically closed, $f(a_1,...,a_(n-1),x_n) in k[x_n]$ has a solution, say $a_n in k$. Then, $(a_1,...,a_(n-1),a_n) in AA^n$ is a solution of $f(x_1,...,x_n)$.

  Then, since $k$ is algebraically closed (in particular infinite), then $AA^(n-1) = k^(n-1)$ (as set) is infinite. Hence, since for each $(a_1,...,a_(n-1)) in AA^(n-1)$, there exists $a_n in k$ such that $(a_1,...,a_(n-1),a_n) in X$ (being a solution to $f$), we conclude that $X$ is infinite.

  \ 


  Now, when $k=CC$, to show that $X$ is non-compact in classical topology, it suffices to show that it's not bounded (since in $CC^n$, with Heine-Borel Theorem it guarantees that $X$ is compact iff it is closed and bounded). For all real number $M>0$, choose $a_1=...=a_(n-1)=M in CC$, since there exists $a_n in CC$ such that $f(a_1,...,a_(n-1),a_n) = 0$, we have $(a_1,...,a_(n-1),a_n) in X$. Which, if consider its norm, we get:
  $ ||(a_1,...,a_(n-1),a_n)|| = sqrt(|a_1|^2 + ... + |a_(n-1)|^2 + |a_n|^2) = sqrt((n-1) dot M^2 + |a_n|^2) >= M sqrt(n-1) >= M $
  (Note: The above requires $n>=2$, or $(n-1)>=1$).

  Hence, for all $M>0$, one can choose $(a_1,...,a_(n-1),a_n) in X$, such that $||(a_1,...,a_(n-1),a_n)||>= M$, showing that $X$ is in fact not bounded, hence not compact in classical topology of $CC^n$.
]

#pagebreak()

= D//3
#problem[
  Hartshorne Chapter 1 Exercise 1.1 (a),(b):

  (a) Let $Y$ be the plane curve $y=x^2$ (i.e. $Y$ is the zero set of the polynomial $f=y-x^2$). Show that $A(Y)$ (or $k[Y]$) is isomorphic to a polynomial ring in one variable over $k$.

  (b) Let $Z$ be the plane curve $x y=1$. Show that $A(Z)$ (or $k[Z]$) is not isomorphic to a polynomial ring in one variable over $k$.
][
  
  #text(weight: "bold")[(a)]: Let ideal $a = (y-x^2) subset.eq k[x,y]$, then we have $Y=Z(a)$ (the corresponding algebraic set of polynomial $y-x^2$, hence also corresponds to the ideal generated by it). Then, $I(Y) = I(Z(a)) = sqrt(a)$, so the coordinate ring $k[Y] = k[x,y]\/sqrt(a)$.

  However, notice that $y-x^2$ is irreducible in $k[x,y]$: If consider $k[x,y] = (k[x])[y]$ (with base ring $k[x]$), then $y-x^2$ has degree of $y$ being $1$, which is irreducible in $(k[x])[y]$. Hence, the ideal $a=(y-x^2)$ is in fact a prime ideal (since the generated element $y-x^2$ is irreducible, and $k[x,y]$ is a UFD), then we get that $sqrt(a)=a$ (since all prime ideal is its own radical).

  Now, to prove that $k[x,y]\/sqrt(a)= k[x,y]\/a tilde.equiv k[t]$ (where $t$ is an indeterminate), consider a ring homomorphism $phi:k[x,y] arrow.r k[t]$ by $phi(f(x,y)) = f(t,t^2)$ for all $f(x,y) in k[x,y]$. 
  Since for all $f(t) in k[t]$, consider $f(x) in k[x] subset.eq k[x,y]$, then $phi(f(x)) = f(t)$, showing $phi$ is surjective, hence $k[t] tilde.equiv k[x,y]\/ker(phi)$.

  Now, to show that $ker(phi)=a$, first, for all $f(x,y) in a$, there exists $g(x,y) in k[x,y]$ such that $f(x,y) = (y-x^2) dot g(x,y)$, hence we have $phi(f(x,y)) = phi((y-x^2) dot g(x,y)) = (t^2-t^2) dot g(t,t^2)=0$, showing $f(x,y) in ker(phi)$, which proves $a subset.eq ker(phi)$;

  On the other hand, if $f(x,y) in ker(phi)$, then $phi(f(x,y)) = f(t,t^2)=0$. So, for all $x in k$, with $y=x^2$ we have $f(x,y) = f(x,x^2)=0$, hence $f(x,y)$ vanishes for all $(x,y) in Y$. This shows that $f(x,y) in I(Y) = sqrt(a)=a$, hence $ker(phi) subset.eq a$. 
  
  As a conclusion, we have $ker(phi)=a$, hence $k[t] tilde.equiv k[x,y]\/ker(phi) = k[x,y]\/a$, while $k[x,y]\/a = k[Y]$ the coordinate ring (due to the fact that $a=sqrt(a)$). Hence, $k[Y] tilde.equiv k[t]$ (polynomial ring with single indeterminate). 

  \ 

  #text(weight: "bold")[(b)]: Given that $Z$ is the plane curve $x y=1$, then $Z$ is the algebraic set corresponding to the polynomial $x y-1 in k[x,y]$. Let ideal $b=(x y-1)$, we have $Z = Z(a)$ (#text(weight: "bold")[Note:] the second $Z$ in $Z(a)$ represents the function of mapping ideal to its algebraic set, not the algebraic set $Z$ itself). Which, we get that $I(Z) = I(Z(b)) = sqrt(b)$, so the corresponding coordinate ring $k[Z] = k[x,y]\/sqrt(b)$.

  Now, again if interpreting $k[x,y] = (k[x])[y]$, since $x y-1$ is a polynomial with degree of $y$ being $1$, it is irreducible in $(k[x])[y]$, hence the ideal $b=(x y-1)$ is in fact a prime ideal, which implies that $sqrt(b)=b$. So, the coordinate ring $k[Z] = k[x,y]\/ sqrt(b)=k[x,y]\/b$.

  Finally, we'll show that $k[Z] tilde.equiv.not k[t]$ the polynomial ring in $k$ with one indeterminate. Suppose the contrary that $k[Z] tilde.equiv k[t]$, then there exists a ring isomorphism $psi:k[Z] = k[x,y]\/b arrow.r k[t]$. Then, if consider $psi(overline(x)),psi(overline(y)) in k[t]$, since $overline(x) dot overline(y) = overline(x y)=1 in k[Z]$ (due to the fact that $x y-1 equiv 0 mod b$, so $overline(x y-1) = 0 in k[Z]$), then we get that $psi(overline(x)) dot psi(overline(y)) = psi(overline(x y))=psi(1) = 1$, hence both $psi(overline(x)),psi(overline(y)) in k[t]$ are invertible. Yet, since group of units $(k[t])^times = k^times$, this enforces $psi(overline(x)),psi(overline(y)) in k^times$ (nonzero constant polynomials), but this is a contradiction since $psi$ is supposed to be surjective, while now $psi(overline(f(x,y))) = f(psi(overline(x)), psi(overline(y))) in k$ for all $overline(f(x,y)) in k[Z]$, showing that $psi$ is not surjective. Hence, we conclude that $k[Z] tilde.equiv.not k[t]$.
]

#pagebreak()

= D//4
#problem[
  Hartshorne Chapter 1 Exercise 1.2:

  #emph[The Twisted Cubic Curve]. Let $Y subset.eq AA^3$ be the set $Y={(t,t^2,t^3)|t in k}$. Show that $Y$ is an affine variety of dimension $1$. Find generators for the ideal $I(Y)$. Show that $A(Y)$ (or $k[Y]$) is isomorphic to a polynomial ring in one variable over $k$. We say that $Y$ is given by the #emph[parametric representation] $x=t,y=t^2,z=t^3$.
][
  First, given any $(x,y,z) in AA^3$, there exists $t in k$ such that $(x,y,z)=(t,t^2,t^3)$ $<==>$ $y=x^2$ and $z=x^3$:

  For $==>$, if there exists $t in k$ such that $(x,y,z) = (t,t^2,t^3)$, it's clear that $y = t^2=x^2$ and $z = t^3=x^3$, so the conditions are satisfied. Conversely (for $<==$), if $y=x^2$ and $z=x^3$, choose $t=x in k$ we have $(x,y,z)=(x,x^2,x^3)=(t,t^2,t^3)$. Hence, the equivalence is shown. Which, it implies that given the ideal $a=(y-x^2, z-x^3)$, the algebraic set $Z(a)=Y$.

  \ 

  Now, our goal is to prove that $k[x,y,z]\/a tilde.equiv k[t]$: 

  Consider the ring homomorphism $phi:k[x,y,z]arrow.r k[t]$ by $phi(f(x,y,z)) = f(t,t^2,t^3)$. Since for all $f(t) in k[t]$, one can consider $f(x) in k[x] subset.eq k[x,y,z]$, which $phi(f(x)) = f(t)$, which shows that $phi$ is surjective, and $k[x,y,z]\/ker(phi) tilde.equiv k[t]$. Which, we want to claim that $ker(phi)=a$.

  For one inclusion, we have the equations $phi(y-x^2) = (t^2 - (t)^2 = 0$ and $phi(z-x^3) = t^3-(t)^3=0$, hence $y-x^2,z-x^3 in ker(phi)$. With all generators of $a$ containing in $ker(phi)$, we have $a subset.eq ker(phi)$.

  The other inclusion can be obtained by certain ways of decomposing the polynomials in $k[x,y,z]$. For that, consider the following lemma:
  #lemma[
    For any monomial $f(x,y,z) in k[x,y,z]$, it can be decomposed into $f_1 dot (y-x^2)+ f_2 dot (z-x^3) + f_3(x)$, where $f_3(x) in k[x] subset.eq k[x,y,z]$.
  ][
    Since all polynomials in $k[x,y,z]$ are finite $k$-linear combinations of monomials, it suffices to prove the case for each monomial $x^m y^n z^l in k[x,y,z]$ (where $m,n,l in NN$ are arbitrary).

    Notice that it can be represents as the following form:
    $ x^m y^n z^l = x^m (x^2 + (y-x^2))^n (x^3 + (z-x^3))^l $
    Which, by performing binomial expansion, we can rewrite $(x^2+(y-x^2))^n$ as follow:
    $ (x^2+(y-x^2))^n = sum_(i=0)^n mat(n; i)(x^2)^i dot (y-x^2)^(n-i) = x^(2n) + (y-x^2)(sum_(i=0)^(n-1)mat(n;i)(x^2)^i(y-x^2)^(n-i)) $
    Hence, $(x^2+(y-x^2))^n = x^(2n)+(y-x^2) dot h_1$ for some $h_1 in k[x,y,z]$. Apply similar logic to the second term we also get $(x^3+(z-x^3))^l = x^(3l)+(z-x^3) dot h_2$ for some $h_2 in k[x,y,z]$. 

    Then, expand out the product, we get:
    $ x^m y^n z^l = x^m (x^(2n)+(y-x^2)dot h_1)(x^(3l)+(z-x^3) dot h_2) $
    $ = (y-x^2) dot x^m dot h_1(x^(3l)+(z-x^3)dot h_2) + x^(2n) dot x^m (x^(3l)+(z-x^3) dot h_2)  $
    $ = (y-x^2) dot g_1 + (z-x^3) dot x^(2n+m) dot h_2 + x^(m+2n+3l) $
    $ = (y-x^2) dot g_1 + (z-x^3) dot g_2 + g_3(x) $
    Where $g_1,g_2 in k[x,y,z]$ and $g_3(x) in k[x]$ are chosen so the above equation is true.

    Since each monomial can be expressed as some form of $(y-x^2)dot g_1+(z-x^3)dot g_2+g_3(x)$, then for any $f in k[x,y,z]$, where $f = sum_(i=1)^l a_i x^(m_i) y^(n_i) z^(l_i)$ for some fixed $a_i in k$ and $m_i,n_i,l_i in NN$, since each $x^(m_i) y^(n_i) z^(l_i) = (y-x^2)dot g_(1,i)+(z-x^3)dot g_(2,i)+g_(3,i)(x)$ based on the above derivation, $f$ can ge brepresented as:
    $ f = sum_(i=1)^n a_i ((y-x^2)dot g_(1,i)+(z-x^3)dot g_(2,i)+g_(3,i)(x)) $
    $ = (y-x^2)sum_(i=1)^n a_i dot g_(1,i)+(z-x^3)sum_(i=1)^n a_i dot g_(2,i)+sum_(i=1)^n a_i dot g_(3,i)(x) $
    Hence, $f = (y-x^2)dot f_1+(z-x^3)dot f_2+ f_3(x)$ for some $f_1,f_2 in k[x,y,z]$, and $f_3(x) in k[x]$.
  ]
  
  Now, based on the above lemma, for all $f in ker(phi)$ can be decomposed into $(y-x^2)dot f_1+(z-x^3)dot f_2+f_3(x)$ for some $f_1,f_2 in k[x,y,z]$ and $f_3(x) in k[x]$. Then, plugin to $phi$ we get:
  $ 0 = phi(f) = phi((y-x^2)dot f_1+(z-x^3)dot f_2+f_3(x)) $
  $ = phi(y-x^2)dot phi(f_1)+phi(z-x^3)dot phi(f_2)+phi(f_3(x)) $
  $ = f_3(t) $
  Hence, with $f_3(t)=0 in k[t]$, $f_3(x)=0$, so $f=(y-x^2)dot f_1+(z-x^3)dot f_2$, showing $f in a$. Therefore, we conclude that $ker(phi) subset.eq a$.

  \ 

  With the two inclusions deduced, we get $a = ker(phi)$, hence $k[t] tilde.equiv k[x,y,z]\/ker(phi)=k[x,y,z]\/a$. Which, this proves that $a$ is in fact a prime ideal (since $k[t]$ is an integral domain), hence $a$ is a radical. So, as a consequence, $I(Y) = I(Z(a)) = sqrt(a)=a$, which shows that $Y$ is an affine variety (since the corresponding ideal $I(Y)=a$ is prime, $Y$ is an irreducible closed subset under Zariski Topology, by #text(weight: "bold")[Corollary 1.4] in Hartshorne).

  \ 

  The above conclusions show that $Y$ is an affine variety, $I(Y) = a = (y-x^2,z-x^3)$ (so ${y-x^2, z-x^3}$ is a set of generators of $I(Y)$), and demonstrated that the coordinate ring $k[Y] = k[x,y,z]\/a tilde.equiv k[t]$ (polynomial ring in one variable over $k$). Now, it's left to demonstrate the dimension of $Y$.

  Based on #text(weight: "bold")[Proposition 1.7] in Hartshorne, given $Y$ as an affine algebraic set, its dimension is the same as the Krull Dimension of its coordinate ring $k[Y]$. Since here $k[Y] tilde.equiv k[t]$, with $k[t]$ being a PID, then $(0)$ is a prime ideal, while any other nonzero prime ideal $P subset.eq k[t]$ is maximal. Hence, the dimension of $k[t]$ is $1$ (since the largest strict increasing chain of prime ideal is $(0) subset.neq P$ for nonzero prime ideal $P subset.eq k[t]$, due to the maximality of $P$). Hence, $Y$ is in fact an algebraic variety of dimension 1, and this finishes all the proof.
]

\ 

= D//5
#problem[
  Hartshorne Chapter 1 Exercise 1.4:

  If we identify $AA^2$ with $AA^1 times AA^1$ in the natural way, show that the Zariski topology on $AA^2$ is not the product topology of the Zariski topologies on the two copies of $AA^1$.
][
  For this we'll prove by contradiction. First, recall the following lemma from point set topology:
  #lemma[
    Given a topological space $X$, and consider $X times X$ under the product topology. Then, the diagonal $Delta = {(x,x) in X times X | x in X}$ is closed under product topology $<==>$ $X$ is Hausdorff.
  ][

    $==>:$ First, suppose $Delta subset.eq X times X$ is closed, which means $(X times X) \\ Delta$ is open in $X times X$ under product topology. Hence, for all $(x,y) in (X times X)\\ Delta$ (with $x!=y$), there exists open neighborhood $U_x,U_y subset.eq X$ of $x,y$ respectively, such that $(x,y) in U_x times U_y subset.eq (X times X)\\ Delta$. Then, for all $z in U_x$ and $w in U_y$, since $(z,w) in U_x times U_y subset.eq (X times X)\\ Delta$, we have $z!=w$, hence $U_x sect U_y = emptyset$. Which, with $x,y in X$ being arbitrary, $x!=y$, $U_x in.rev x$ and $U_y in.rev y$ are open neighborhoods that're disjoint, hence $X$ is Hausdorff.

    $<==:$ Suppose $X$ is Hausdorff, then for all $(x,y) in (X times X)\\ Delta$ (where $x!= y$), there exists open neighborhoods $U_x,U_y subset.eq X$ of $x,y$ respectively, such that $U_x sect U_y = emptyset$. Hence, for all $(z,w) in U_x times U_y$, with $z in U_x$ and $w in U_y$, the two sets being disjoint implies $z!=w$, hence $(z,w) in (X times X)\\Delta$. Hence, $(x,y) in U_x times U_y subset.eq (X times X)\\ Delta$, showing that $(X times X)\\Delta$ is open in $X times X$ under product topology, hence $Delta subset.eq X times X$ is closed under product topology.
  ]
  With this lemma in mind, suppose the contrary that the Zariski Topology on $AA^2$ is the same as the product topology of $AA^1 times AA^1$ (with $AA^1$ equipped with its own Zariski Topology). Then, by the lemma above, the diagonal $Delta = {(x,x) in AA^2 | x in k} subset.eq AA^2$ is closed in $AA^2$ $<==>$ $AA^1$ is Hausdorff under Zariski Topology. Now, we can derive the following statements:

  \ 

  #text(weight: "bold")[1. $AA^1$ is Hausdorff under Zariski Topology:]

  Notice that with the polynomial $y-x in k[x,y]$, the corresponding algebraic set $Z(y-x) = Delta$ (since $(x,y) in AA^2$ satisfies $y-x=0$ iff $y=x$ iff $(x,y) in Delta$). Hence, $Delta$ itself is closed in $AA^2$ under Zariski Topology, so based on our assumption above, $AA^1$ is Hausdorff.

  \ 

  #text(weight: "bold")[2. $AA^1$ has Zariski Topology $=$ Finite Complement Topology:]
  
  Since $k[x]$ is a PID (given that $k$ is a field), then for any nonempty and proper algebraic set $Y subset.eq AA^1 = k$, its corresponding ideal $I(Y) = (f(x))$ for some $f(x) in k[x]$, hence $t in Y$ iff $f(t)=0$, or $t$ is a zero of $f(x)$. Since $f(x)$ only has finitely many roots, it follows that $Y$ is finite. Conversely, given any nonempty finite subset $X subset.neq AA^1$, let $f(x):= product_(a in X)(x-a)$, we have $X$ being the algebraic set corresponding to $f(x)$ (since $a in X$ iff $f(a)=0$). Hence, the closed set in $AA^1$ under Zariski Topology (beside $AA^1$ and $emptyset$) are all finite subsets of $AA^1$, showing that all open sets in $AA^1$ (besides $emptyset$ and $AA^1$ itself) are precisely the subsets with their complements being finite, hence the Zariski Topology on $AA^1$ is equivalent to the Finite Complement Topology.

  \ 
  
  #text(weight: "bold")[3. $AA^1$ with Finite Complement Topology is Not Hausdorff:]
  Then, given $AA^1 = k$ is infinite (due to the assumption that $k$ is algebraically closed), the Finite Complement Topology on $AA^1$ is not Hausdorff: Suppose the contrary that it is Hausdorff, then for any $x,y in AA^1$ with $x!=y$, there exists open neighborhoods $U_x, U_y subset.eq AA^1$ containing $x,y$ respectively, such that $U_x sect U_y = emptyset$. However, it implies that $U_y subset.eq AA^1 \\ U_x$, while $AA^1 \\ U_x$ is finite, hence $U_y$ is finite. Yet, this implies that $AA^1 \\ U_y$ is infinite (since $AA^1$ is infinite, while $U_y$ is finite), which reaches a contradiction (since $U_y$ is open, which suppose to have finite complement). So, $AA^1$ cannot be Hausdorff.

  \ 

  However, this contradicts one of the previous conclusions that $AA^1$ is Hausdorff. Hence, the initial assumption must be false, showing that Zariski Topology on $AA^2$ is not the same as product topology of $AA^1 times AA^1$ (with $AA^1$ equipped with its own Zariski Topology).

  \ 

  //(This also implies that Zariski Topology on $AA^2$ is finer than the product topology of $AA^1 times AA^1$, since product topology is supposedly the coarsest topology with two projection maps being continuous, while product of two arbitrary algebraic sets is still an algebraic set).
  (I think Here we can conclude that $AA^2$ has Zariski Topology being the same as product topology of $AA^1 times AA^1$ iff the base field $k$ is finite, since this is the only case where the Finite Complement Topology, i.e. the Zariski Topology on $AA^1$, is Hausdorff).
]

#pagebreak()

= D//6
#problem[
  Hartshorne Chapter 1 Exercise 1.5:

  Show that a $k$-algebra $B$ is isomorphic to the affine coordinate ring of some algebraic set in $AA^n$ for some $n$ if and only if $B$ is a finitely generated $k$-algebra with no nilpotent elements.
][

  $==>:$ Suppose $B$ is a $k$-algebra (here $B$ can be assumed as a commutative algebra) that is isomorphic to the affine coordinate ring of some algebraic set in $AA^n$ for some $n$.

  Then, there exists an algebraic set $Y subset.eq AA^n$, such that $B tilde.equiv k[Y]$, where let $J = I(Y) subset.eq k[x_1,...,x_n]$ the corresponding ideal (which $J$ is a radical), we have $k[Y] = k[x_1,...,x_n]\/ J$. This shows that $B$ is a finitely generated $k$-algebra (since it's isomorphic to a quotient of the polynomial ring $k[x_1,...,x_n]$), and also $B$ has no nilpotent elements (since $J$ is a radical ideal, so for all $f in k[x_1,...,x_n]$, if the quotient $overline(f) in k[Y]$ satisfies $overline(f)^k = 0$ for some $k in NN$, then $f^k in J$, hence $f in J$ since $J$ is a radical, or $overline(f)=0$). This proves the forward implication.

  \ 

  $<==:$ Now, suppose $B$ is a finitely generated $k$-algebra with no nilpotent elements, then there exists $a_1,...,a_n in B$, such that for every elemnt $b in B$, there exists a polynomial $f in k[x_1,...,x_n]$ such that $b = f(a_1,...,a_n)$. Hence, if consider the ring homomorphism $phi:k[x_1,...,x_n] arrow.r B$ by $phi(f) = f(a_1,...,a_n)$, the ring homomorphism $phi$ is surjective, showing that $B tilde.equiv k[x_1,...,x_n]\/ker(phi)$. 

  Also, the assumption that $B$ has no nilpotent elements implies that $ker(phi) subset.eq k[x_1,...,x_n]$ is a radical (since for all $f in k[x_1,...,x_n]$, if $f^k in ker(phi)$ for some $k in NN$, we have $phi(f)^k = phi(f^k) = 0$, showing that $phi(f) in B$ is nilpotent, or $phi(f)=0$. Hence $f in ker(phi)$, therefore $sqrt(ker(phi))=ker(phi)$).

  Then, if we take $Y = Z(ker(phi)) subset.eq AA^n$ as the algebraic set, since $ker(phi) = I(Y) = I(Z(ker(phi)))$ (due to $ker(phi)$ being a radical), we have the coordinate ring $k[Y] = k[x_1,...,x_n]\/ ker(phi)$, hence $B tilde.equiv k[x_1,...,x_n]\/ker(phi) = k[Y]$, so $B$ is isomorphic to the affine coordinate ring of some algebraic set in $AA^n$ (for some $n in NN$). This proves the converse.

  
]